---
layout: post
title: Item 9 Prefer try-with-resources to try-finally
---

Java类库中包含了很多资源，必须通过调用 close() 方法来关闭。像InputStream, OutputStream, java.sql.Connection。
关闭资源这事经常被程序员忽视，在性能上将会出现可怕的后果。然而很多资源使用 finalizers 作为安全保障，
但是 finalizers 往往不能很好地工作。 

从以往来看，try-finally 语句已经是确保资源可以正确关闭的最好方式，即使返回的时候有异常:

```java
// try-finally - No longer the best way to close resources!
static String firstLineOfFile(String path) throws IOException {
    BufferedReader br = new BufferedReader(new FileReader(path));
    try {
        return br.readLine();
    } finally {
        br.close();
    }
}
```

这看着也许并没有那么糟糕，但是当你再增加一个资源的时候，会变得更糟：  
//下面的代码看起来太丑了

```java
// try-finally is ugly when used with more than one resource!
static void copy(String src, String dst) throws IOException {
    InputStream in = new FileInputStream(src);
    try {
        OutputStream out = new FileOutputStream(dst);
        try {
            byte[] buf = new byte[BUFFER_SIZE];
            int n;
            while ((n = in.read(buf)) >= 0)
                out.write(buf, 0, n);
        } finally {
            out.close();
        }
    } finally {
        in.close();
    }
}
```

很难相信，即使是优秀的程序员也会时常犯这样的错误。首先，在 《Java Puzzlers》 的 第88页，我就出现了这样的错误，
这么多年竟然没人注意到。事实上，早在2007年的时候，Java类库中针对close()方法，三分之二的使用是错的。

在前两个代码示例中，即使用 try-finally 语句关闭资源，仍然有细微的缺陷。try 和 finally 块中的代码还是抛出了异常。
例如：在 firstLineOfFile() 方法中，调用 readLine() 方法时， 可能会因为底层物理设备的故障而抛出异常；
调用 close() 方法时，也可能出于同样的原因而失败。在这种情况下，第二个异常会完全覆盖住第一个异常。
在异常堆栈中没有记录第一个异常信息，这在实际系统中调试的时候会非常地复杂，通常这是你在诊断问题时想要看到的第一个
异常信息。可以写代码来抑制第二个异常同时支持第一个异常，但几乎没人这么做，因为这样太冗余了。

当Java 7 引进 try-with-resources 语句时，所以这些问题一下子就被解决了。可以使用这个结构，前提是资源必须
实现 AutoCloseable 接口，该接口只有一个方法 void close()。现在，Java 类库和第三方类库中的许多类和接口
实现或者扩展了 AutoCloseable。如果你自己写一个表示必须关闭资源的类，这个类也应该实现 AutoCloseable。

下面是我们的第一个例子如何使用 try-with-resources 结构:

```java
// try-with-resources - the the best way to close resources!
static String firstLineOfFile(String path) throws IOException {
    try (BufferedReader br = new BufferedReader(new FileReader(path))) {
        return br.readLine();
    }
}
```

下面是我们的第二个例子如何使用 try-with-resources 结构:

```java
// try-with-resources on multiple resources - short and sweet
static void copy(String src, String dst) throws IOException {
    try (InputStream in = new FileInputStream(src);
            OutputStream out = new FileOutputStream(dst)) {
        byte[] buf = new byte[BUFFER_SIZE];
        int n;
        while ((n = in.read(buf)) >= 0)
            out.write(buf, 0, n);
    }
}
```

try-with-resources 这个版本相比于原来的，不但简短，更易读，而且提供更好的诊断。想想 firstLineOfFile() 方法，
如果 readLine() 和 （隐藏的）close() 调用都抛出了异常，后面的异常被抑制支持前者。其实，许多的异常会被抑制为的是
保护你实际上想看到的异常。这些抑制的异常不是被丢弃了，在 Java 7 中，可以通过 Throwable 类的 getSuppressed()使用。

可以给 try-with-resources 语句增加 catch 子句，就像在常规的 try-finally 语句中一样。这就允许你在处理异常情况下，
不需要用另一层嵌套污染代码。作为一个有点不自然的示例，这个版本的 firstLineOfFile() 方法不抛出异常，但是会返回一个
默认值如果不能打开或者读取文件：

```java
// try-with-resources with a catch clause
static String  firstLineOfFile(String path, String defaultVal) {
    try (BufferedReader br = new BufferedReader(new FileReader(path))) {
        return br.readLine();
    } catch (IOException e) {
        return defaultVal;
    }
}
```

小结：当处理必须关闭的资源时，总是使用 try-with-resources 优先于 try-finally。这样写出的代码更短，更清晰，产生的
异常更有用。try-with-resources 语句对使用必须关闭的资源，更容易写出正确的代码，反观用 try-finally 是几乎不可能的。
